version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: piapp_db
    environment:
      POSTGRES_DB: piapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: piapp_backend
    environment:
      PORT: 5050
      CORS_ORIGIN: "*"
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: piapp
      PGSSL: "false"
      WEBHOOK_SECRET: dev_secret
      # Set these to enable real server-side verification against Pi APIs
      PI_API_BASE: ""
      PI_API_SECRET: ""
    ports:
      - "5050:5050"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:


